name: PHPStan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.0', '8.1', '8.2', '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: igbinary
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: vendor/bin/phpstan analyse
