name: PHPStan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-8.4-${{ hashFiles('composer.lock', 'composer.json') }}
          restore-keys: |
            composer-8.4-
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: vendor/bin/phpstan analyse
