name: PHPUnit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3', '8.4' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: igbinary
      - uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ matrix.php-version }}-${{ hashFiles('composer.lock', 'composer.json') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: vendor/bin/phpunit
